### ISSUE TITLE
TypeError: document.getCSSCanvasContext is not a function

### ISSUE THREAD

**Issue by DarkDaskin** [artygus/webkit-webinspector#1]
The `document.getCSSCanvasContext` function was removed from Chrome 48+. This causes the web inspector to crash with that error message.

This function was used to draw some graphic elements by setting `background-image: -webkit-canvas` in their style. Such constructs should be replaced by either static images or generated on the fly and referenced in styles by another mechanism (e.g. data or blob URLs).

At best WebKit code should be patched automatically on build, so it could be easily updated.

**Comment by artygus** [comment]
thanks for the report @DarkDaskin, I think I'll go with a few return statements instead for now
